import Navbar from "@/components/navbar";
import SideBar from "@/components/side-bar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CloudinaryLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Navbar />
        <main className="flex">
          <SideBar />
          <div className="w-full p-4">{children}</div>
        </main>
      </body>
    </html>
  );
}
